= FBSN: Friend Backup Snapshotting Network
v0.1 2016-07-31
Jonathan Zacsh, <jzacsh@gmail.com>
:grandurl: link:doc/design.adoc
:laborurl: link:doc/labor.adoc
:log2rotate: link:src/log2rotate
:daemonflow: link:doc/remotedrivedaemon.adoc
:O: pass:normal[ {nbsp} ]
:D: pass:normal[ &#10004; ]

Backups: Robust, Easy(?), Multi-homed, FOSS. Hot-off-the-press vaporware
(seriously, look away).

== Status

I'm currently not achieving any of my {grandurl}[lofty goals], so if you're
hoping for a useable program to run, avert your eyes.

However, you may find this useful at least as documentation, for the moment: a
collection of how-tos, surrounding a single goal. That goal, in a one run-on
sentence:

.End-Use Vision
[[enduse]]
____
Friends/family mail each high-capacity thumbdrives, w/their public keys in `/`
directory, and with no further configuration: backup services added/removed by
plugging/unplugging said drive. I particularly want *non*-programmer friends
feeling empowered to host!
____

Though, I haven't reached the parts I truly find interesting in this goal -
_auto-detection of keys, auto-configuration, etc._ - I just finished working
through {laborurl}[tediously documenting] all of the details in setting up an
auto-snapshotting rsync receptical.

=== tl;dr
Currently at documentation/research stages. Peer into my notes, on a
push-to-server rsnapshot solution {laborurl}[`labor.adoc`] (<<serverlabor,
summary>>), and feel free to ping me on #freenode (jzaksh@)

=== Roadmap
To get to my <<enduse, envisioned use-case>>, I'm roughly following these steps:

- {D} get feedback and {grandurl}[roughly outline a high-level design]
- {D} Installer: {laborurl}[setup/document single-user backup]:
      rsync, snapshotting, plug PC-config, etc. +
      -- _As of 2016-07-15, have been backing up automatically_

- {O} *current*: Installer: use said doc to automate single-user setup +
      -- _As of 2016-07-31, enlisted someone to host 2nd setup remote to me_

- {O} replace rsnapshot w/configurable-length {log2rotate}[`src/log2rotate`]
- {D} Daemon: {daemonflow}[rough implementation sketch] of automating HDD confs
- {O} Daemon: v0 implementatino of auto-management
- {O} Daemon: API to allow single-user to manage their drive/settings remotely
- {O} Daemon: Exclude repo's key from rsync _(maybe default, probably user
  configurable)_
  footnoteref:[repokey, Both borgbackup and restic maintain a
  passphrase-protected private key side-by-side with their repo contents which
  currently gets synced to server]

== (Imagined) FAQ
Can I use this? What does it do?::
  Nope, you can't use this. This repo doesn't do much, yet. But I'd love to hear
  from you if you *have* read on, and you're still interested!
Why release?? You have nothing to show!::
  Because I was feeling cramped in the massive "private" gist I was developing
  in. Working without directories is hard.
What's the tl;dr of your `labor.adoc` progress?::
  Good! I currently have `rsync ./stuff/ host:` automagically snapshotting, so
  my hopes are high! See more in that doc's, "TODO List for `ForceCommand`"
Bash?::
  I'll happily port stuff to golang, but for now everything is small and I'm
  fine with it. The aggressive daemon I plan to build will definitely be written
  in golang from the start.

== Backup Infrastructure Goals:
.Backups...
. I can trust run well
  footnoteref:[trust, By "trust" I mean designed once and only once]
. I don't have to think about
  footnoteref:[debug, Called "debuggability" in other notes]
. Mirror a professional solution I could imagine paying others to maintain
  footnoteref:[sre, "Maintain" does not mean "fork then enterprise-version-ify";
  I a want *complete* solution that would only require SREs because the need for
  *someone* to watch and debug a system is just an unavoidable]
. I *could* host without any loss in quality
  footnoteref:[qualityloss, Aside from the fact that I'm less reliable than a
  team of people I would be paying a fee to :P]

== Under Construction - Prototyping Efforts

=== 2016-06-28: sshd Watch Daemon

.Local Scripting Prototyping Files
. `backup-to-disk_daemon.rules`
. `prototype-sshd-mod.sh`
. `prototype-sshd-watch.sh`

[source, sh]
  debugrule="$(readlink -f 10-DEBUGGING-backup.rules)"
  pushd /etc/udev/rules.d/
  sudo ln -sv "$debugrule" 10-DEBUGGING-backup.rules
  popd
  sudo udevadm control --reload

=== 2016-07-02: rsync to many hosts

[source, sh]
----
$ ./sync_to_mirrors -h
usage: `sync_to_mirrors SOURCE_DIR [DEST_DIR_SUFFIX]`

  Runs rsync from SOURCE_DIR to each host in "$XDG_CONFIG_HOME/backupto.hosts";

  Uses rsync(1) flags:
     --verbose  --recursive  --delete  --archive  --acls  --xattrs

  Optionally: list rsync(1) excludes, one per line in "$XDG_CONFIG_HOME/backupto.excludes"
----

[[serverlabor]]
=== 2016-07-03: Rsync & Rotation - `doc/labor.adoc`
Though my end-goal  is as hands-off as possible, I have to start somewhere, so
I'm {laborurl}[documenting all of the *manual* labor involved in setting
up the underlying system]. The setup is what I'd fundamentally like to automate,
so this documentation effort will help in a few ways:

. should clarify *what* value I'm trying to add
  (eg: I'm not re-inventing snapshotting)
. should clarify how much labor is involved
. should serve as great task-list when tackling the ultimate automation
